//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bet()
        {
            this.BetPrognostics = new HashSet<BetPrognostic>();
        }
    
        public long Id { get; set; }
        public int Week { get; set; }
        public Nullable<int> Journey { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public decimal ShareTo1 { get; set; }
        public decimal ShareToX { get; set; }
        public decimal ShareTo2 { get; set; }
        public string Choice { get; set; }
        public string Result { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BetPrognostic> BetPrognostics { get; set; }
    }
}
