//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetPrognostic
    {
        public long Id { get; set; }
        public long BetId { get; set; }
        public int Matchs { get; set; }
        public decimal HomePercent { get; set; }
        public decimal AwayPercent { get; set; }
        public decimal TotalPercent { get; set; }
        public decimal Share { get; set; }
        public string Condition { get; set; }
    
        public virtual Bet Bet { get; set; }
    }
}
