//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FootbalEntities : DbContext
    {
        public FootbalEntities()
            : base("name=FootbalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Partido> Partidos { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Temporada> Temporadas { get; set; }
        public virtual DbSet<Liga> Ligas { get; set; }
        public virtual DbSet<Bet> Bets { get; set; }
        public virtual DbSet<Jornada> Jornadas { get; set; }
        public virtual DbSet<BetPrognostic> BetPrognostics { get; set; }
    }
}
